apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: integration-suite-test-application-vlup
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: integration-suite-test-component-git-source-wumm
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: integration-suite-test-component-git-source-wumm
  namespace: integration-e2e-83b46129-4cad-4d9c-8281-e7ad51201c74
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: integration-suite-test-component-git-source-wumm
status:
  configuration:
    generatedName: ""
