apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: integration-suite-test-component-git-source-wumm
  namespace: integration-e2e-83b46129-4cad-4d9c-8281-e7ad51201c74
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: integration-suite-test-application-vlup
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: integration-suite-test-component-git-source-wumm
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: integration-suite-test-component-git-source-wumm-
      labels:
        build.appstudio.openshift.io/application: integration-suite-test-application-vlup
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: integration-suite-test-component-git-source-wumm
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: integration-e2e-83b46129-4cad-4d9c-8281-e7ad51201c74
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/psturc/test-images:79af0cd208f44cde995388f410efbcd7-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: integration-suite-test-component-git-source-wumm/$(tt.params.git-revision)
    status: {}
status: {}
